/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inspectorlogbook;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author 19950014
 */
public class frame_attachment extends javax.swing.JFrame {

    /**
     * Creates new form frame_attachment
     */
    public frame_attachment() {
        initComponents();        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setModalExclusionType(null);
       
    }
    public void showAttachments(String cono){
        try{
        TableModel tamod = jt_attachments.getModel();
        jt_attachments.setModel(new Attachments().setTable(tamod, cono));        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "EXCEPTION IN showAttachment :: "+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_attachments = new javax.swing.JTable();
        btn_deleteAttachments = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jt_attachments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jt_attachments.setRowHeight(16);
        jt_attachments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "aid", "/", "CONTROL No", "ATTACHMENT", "filePath"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_attachments.getTableHeader().setBackground(new java.awt.Color(0,63,94));
        jt_attachments.getTableHeader().setForeground(new java.awt.Color(255,255,255));
        jt_attachments.getTableHeader().setFont(new java.awt.Font("Tahoma",1,14));
        jt_attachments.setFillsViewportHeight(true);
        jt_attachments.setRowHeight(24);
        jt_attachments.getTableHeader().setReorderingAllowed(false);
        jt_attachments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_attachmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_attachments);
        if (jt_attachments.getColumnModel().getColumnCount() > 0) {
            jt_attachments.getColumnModel().getColumn(0).setMinWidth(0);
            jt_attachments.getColumnModel().getColumn(0).setPreferredWidth(0);
            jt_attachments.getColumnModel().getColumn(0).setMaxWidth(0);
            jt_attachments.getColumnModel().getColumn(1).setMinWidth(20);
            jt_attachments.getColumnModel().getColumn(1).setPreferredWidth(20);
            jt_attachments.getColumnModel().getColumn(1).setMaxWidth(20);
            jt_attachments.getColumnModel().getColumn(2).setMinWidth(0);
            jt_attachments.getColumnModel().getColumn(2).setPreferredWidth(0);
            jt_attachments.getColumnModel().getColumn(2).setMaxWidth(0);
            jt_attachments.getColumnModel().getColumn(4).setMinWidth(0);
            jt_attachments.getColumnModel().getColumn(4).setPreferredWidth(0);
            jt_attachments.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btn_deleteAttachments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/delete.png"))); // NOI18N
        btn_deleteAttachments.setText("DELETE");
        btn_deleteAttachments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAttachmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_deleteAttachments, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btn_deleteAttachments)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_attachmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_attachmentsMouseClicked
        try{
            int row = jt_attachments.getSelectedRow();
            int col = jt_attachments.getColumnModel().getSelectionModel().getAnchorSelectionIndex();
            if(col == 3){
            String filepath =  jt_attachments.getModel().getValueAt(row, 4).toString();
            
            
            File file = new File(filepath);
            Desktop desktop = Desktop.getDesktop();
        
        if(file.exists()){ 
            try {
            desktop.open(file);
            } catch (IOException ex) {
                 JOptionPane.showMessageDialog(null, "Error displaying file..."+ex);
               // Logger.getLogger(ViolationAndPenaltyGuide.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
            
            
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jt_attachmentsMouseClicked

    private void btn_deleteAttachmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAttachmentsActionPerformed
        int attid;
        String contl="";
        try{
            int rowcount = jt_attachments.getRowCount();
            int count = 0;
            for(int i = 0 ; i < rowcount ; i++){
                if(((boolean)jt_attachments.getValueAt(i, 1))==true){
                 String nameOfile = jt_attachments.getValueAt(i,4).toString();
                //JOptionPane.showMessageDialog(null , tbl_Attachments.getValueAt(i, 1) +"  "+ tbl_Attachments.getValueAt(i, 2)+"  "+tbl_Attachments.getValueAt(i,3));
                attid = Integer.parseInt(jt_attachments.getValueAt(i,0).toString());
                contl = jt_attachments.getValueAt(i, 2).toString();
                deleteAttachments(attid);
                
                //delete the file
                try{
                    File file = new File(nameOfile);
                    //JOptionPane.showMessageDialog(null,nameOfile);
                    if(file.delete()){
                       //JOptionPane.showMessageDialog(null,file.getName()+" cancelled.");
                    }
            
                }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
                }
                //delete the file -//
                count++;
                
                }
                
            }
            showAttachments(contl);
            
            //setAttachmentsTable(ri, resql);
            if(count > 0){
                JOptionPane.showMessageDialog(null, count + "  Attachment removed!");
                //ViolationAndPenaltyGuide vap = new ViolationAndPenaltyGuide();
                //vap.countAttachment2();
            }else if(count == 0){
                JOptionPane.showMessageDialog(null, count + " Attachment removed! \n or "
                        + "you should select a file to be removed.");
            }
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error :: btn_deleteAttachementActionPerformed = "+e);
        }
    }//GEN-LAST:event_btn_deleteAttachmentsActionPerformed
    public void deleteAttachments(int at_id){
        
        String sql = "DELETE FROM tb_attachments WHERE at_id = ?";
        PreparedStatement ps = null;
        Connection con;
        try{
            
            con = ConnectDB();
            ps = con.prepareStatement(sql);
            ps.setInt(1, at_id);
            ps.executeUpdate();
            
            ps.close();
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error :: deleteAttachments = "+ e);
        }
    }
    public Connection ConnectDB() {
            Connection con = null;
		try {
			
                        Class.forName("org.sqlite.JDBC");
                        con = DriverManager.getConnection("jdbc:sqlite:C:\\PLB\\InspectorLogbook\\db\\insplbdb.sqlite");
		
                }catch(ClassNotFoundException | SQLException e){
				JOptionPane.showMessageDialog(null, "Error in getConnection: "+e);
		}			
            return con;
}
    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_attachment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_attachment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_attachment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_attachment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       */ //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
          //      new frame_attachment().setVisible(true);
        //    }
       // });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteAttachments;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_attachments;
    // End of variables declaration//GEN-END:variables
}
